name: chat_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  image_picker: ^1.1.2
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  flutter_image_compress: ^2.4.0
  go_router: ^14.8.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  toastification: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf