// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiaj3DVjRz02sCUKeoUTm9j6dZfhCfadk',
    appId: '1:396786510954:web:439eee21522a6290d1ae13',
    messagingSenderId: '396786510954',
    projectId: 'chat-app-bdb28',
    authDomain: 'chat-app-bdb28.firebaseapp.com',
    storageBucket: 'chat-app-bdb28.firebasestorage.app',
    measurementId: 'G-VR8B91XZ6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXkEbrWHo9LzP9k-DHdjeLh-ykp8ciM3Q',
    appId: '1:396786510954:android:edb2f9db2d1b9870d1ae13',
    messagingSenderId: '396786510954',
    projectId: 'chat-app-bdb28',
    storageBucket: 'chat-app-bdb28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKE-PP0w5VgsBf8hB5_FMxPNpG7k8NB8',
    appId: '1:396786510954:ios:371baf265b04d19dd1ae13',
    messagingSenderId: '396786510954',
    projectId: 'chat-app-bdb28',
    storageBucket: 'chat-app-bdb28.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYKE-PP0w5VgsBf8hB5_FMxPNpG7k8NB8',
    appId: '1:396786510954:ios:371baf265b04d19dd1ae13',
    messagingSenderId: '396786510954',
    projectId: 'chat-app-bdb28',
    storageBucket: 'chat-app-bdb28.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiaj3DVjRz02sCUKeoUTm9j6dZfhCfadk',
    appId: '1:396786510954:web:ef04191a81944d40d1ae13',
    messagingSenderId: '396786510954',
    projectId: 'chat-app-bdb28',
    authDomain: 'chat-app-bdb28.firebaseapp.com',
    storageBucket: 'chat-app-bdb28.firebasestorage.app',
    measurementId: 'G-VMSCYV8D9G',
  );
}
